apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: neutral-kangaroo-python
  janus-idp.io/tekton: neutral-kangaroo-python
  backstage.io/kubernetes-id: neutral-kangaroo-python
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: neutral-kangaroo-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
